name: CRM CI & Release Prep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Build & Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: TypeScript compile check
        working-directory: ./backend
        run: npx tsc --noEmit

      - name: Lint backend
        working-directory: ./backend
        run: npm run lint

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
changelog:
  name: Generate Changelog
  runs-on: ubuntu-latest
  needs: [backend, frontend]
  if: github.ref == 'refs/heads/main' && success()

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install standard-version
      run: npm install --global standard-version

    - name: Generate changelog and bump version
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        npx standard-version --skip.tag

    - name: Commit changelog changes
      run: |
        git add CHANGELOG.md package.json package-lock.json || true
        git commit -m "chore(release): update changelog [skip ci]" || echo "No changes to commit"
        git push origin main
