name: "CRM CI & Release Prep"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Build & Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: TypeScript compile check
        working-directory: ./backend
        run: npx tsc --noEmit

      - name: Lint backend
        working-directory: ./backend
        run: npm run lint

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
   changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main' && success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install standard-version
        run: npm install --global standard-version

      - name: Generate changelog and bump version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx standard-version --skip.tag

      - name: Commit changelog changes
        run: |
          # Add changelog if present
          if [ -f CHANGELOG.md ]; then git add CHANGELOG.md; fi

          # Add backend lock/version files if they exist
          if [ -f backend/package.json ]; then git add backend/package.json; fi
          if [ -f backend/package-lock.json ]; then git add backend/package-lock.json; fi

          # Add frontend lock/version files if they exist
          if [ -f frontend/package.json ]; then git add frontend/package.json; fi
          if [ -f frontend/package-lock.json ]; then git add frontend/package-lock.json; fi

          git commit -m "chore(release): update changelog [skip ci]" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main